### PR TITLE
Upgrading to Metabase v.0.50.12

### PR DESCRIPTION
**Pull request by jurasan**
I tested it on Metabase v0.50.12 for a while and all features seem to work.
But I don't know how to run unit tests.

### CODE REVIEW

**Comment by joseantolinqida** [comment]
Is there any estimated time for this PR to get merged @relferreira ?

Thank you for the amazing work!!

**Review by relferreira — APPROVED** [review]

**Comment by borft** [comment]
> Good stuff, thanks for your efforts. Will test it over here. Hopefully @relferreira can check and merge!

1. Thanks for merging :+1: 
2. I've tested against the latest build (`v0.50.22` at this time), and it's working fine for me!

**Comment by relferreira** [comment]
Thank you for the contribution, and I am sorry for the delay.

I don't use Databricks or Metabase daily anymore, so it's hard for me to keep this driver updated :(

**Comment by borft** [comment]
> Thank you for the contribution, and I am sorry for the delay.
> 
> I don't use Databricks or Metabase daily anymore, so it's hard for me to keep this driver updated :(

I can imagine. I do use them, but don't understand much of Clojure ;)

**Pull request merged**
